I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 391, in script
    daniel "yo whats up guys"
Exception: Sayer 'daniel' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 391, in script
    daniel "yo whats up guys"
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'daniel' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Gwetome Academy 1.0
Mon Feb 19 16:24:45 2024
