I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 433, in script
    mom "Good morning! I made you breakfast since I knew you'd wake up late."
Exception: Sayer 'mom' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 433, in script
    mom "Good morning! I made you breakfast since I knew you'd wake up late."
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.1-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.1-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'mom' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Gwetome Academy 1.0
Sun Mar 24 00:42:26 2024
