I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 33, in script
    init python:
  File "game/script.rpy", line 89, in <module>
    if renpy.get_say_attributes().who == mc:
AttributeError: 'NoneType' object has no attribute 'who'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 33, in script
    init python:
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 89, in <module>
    if renpy.get_say_attributes().who == mc:
AttributeError: 'NoneType' object has no attribute 'who'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Gwetome Academy 1.0
Sun Feb  4 01:24:28 2024
