I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 296, in script
    mc (pajamas ecstatic) "It`s hard not to when you`re given so many choices, especially when you can punch the male leads. Hehehe!"#Gwyn2
Exception: Sayer 'mc (pajamas ecstatic)' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 296, in script
    mc (pajamas ecstatic) "It`s hard not to when you`re given so many choices, especially when you can punch the male leads. Hehehe!"#Gwyn2
  File "C:\Users\jtgru\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\jtgru\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'mc (pajamas ecstatic)' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Gwetome Academy 1.0
Wed Dec 20 15:03:43 2023
